<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Saeeda" failures="5" tests="5" name="API Regression" time="5.156" errors="0" timestamp="2025-07-28T14:19:20 EDT">
  <testcase classname="api.CreateItemAPITests" name="createItem" time="0.606">
    <failure type="java.lang.AssertionError" message="expected [201] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [500]
at api.CreateItemAPITests.createItem(CreateItemAPITests.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- createItem -->
  <testcase classname="api.EditItemAPITests" name="editItem" time="0.023">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at api.EditItemAPITests.editItem(EditItemAPITests.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- editItem -->
  <testcase classname="api.DeleteItemAPITests" name="deleteItem" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at api.DeleteItemAPITests.deleteItem(DeleteItemAPITests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteItem -->
  <testcase classname="ui.LoginTests" name="loginWithInvalidCredentials" time="0.246">
    <failure type="java.lang.AssertionError" message="Expected error message not found. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected error message not found. expected [true] but found [false]
at ui.LoginTests.loginWithInvalidCredentials(LoginTests.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
  <testcase classname="ui.LoginTests" name="loginWithValidCredentials" time="0.206">
    <failure type="java.lang.AssertionError" message="Login failed with valid credentials. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login failed with valid credentials. expected [true] but found [false]
at ui.LoginTests.loginWithValidCredentials(LoginTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginWithValidCredentials -->
</testsuite> <!-- API Regression -->
